objects/Main/objects/WSU_Kyou_Info__c.object
<!--
This file is part of WSU_Kyou, a Salesforce native queue for Batch Apex and Scheduled Apex.

Copyright 2013-2014, Wayne State University
License: 3-clause BSD license.  See LICENSE.
-->
<CustomObject>
    <description>Stores information about the state of entries in the Kyou.</description>
    <label>Kyou Info</label>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Lowest_Priority__c</fullName>
        <label>Lowest Priority</label>
        <type>Number</type>
        <precision>18</precision>
        <scale>0</scale>
    </fields>
    <fields>
        <fullName>Highest_Priority__c</fullName>
        <label>Highest Priority</label>
        <type>Number</type>
        <precision>18</precision>
        <scale>0</scale>
    </fields>
    <fields>
        <fullName>Locked__c</fullName>
        <label>Locked</label>
        <type>Checkbox</type>
        <defaultValue>false</defaultValue>
    </fields>
</CustomObject>

objects/Main/objects/WSU_Kyou_Open_Slots__c.object
<!--
This file is part of WSU_Kyou, a Salesforce native queue for Batch Apex and Scheduled Apex.

Copyright 2013-2014, Wayne State University
License: 3-clause BSD license.  See LICENSE.
-->
<CustomObject>
    <description>Tracks open priority slots Kyou.</description>
    <label>Kyou Open Slots</label>
    <nameField>
        <label>Open Slots ID</label>
        <type>AutoNumber</type>
        <displayFormat>K_OS-{0}</displayFormat>
    </nameField>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <type>LongTextArea</type>
        <length>32768</length>
    </fields>
    <pluralLabel>Kyou Open Slots Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Main/objects/WSU_Kyou_QueueEntry__c.object
<!--
This file is part of WSU_Kyou, a Salesforce native queue for Batch Apex and Scheduled Apex.

Copyright 2013-2014, Wayne State University
License: 3-clause BSD license.  See LICENSE.
-->
<CustomObject>
    <description>Entry in a Queue for Kyou.</description>
    <label>Queue Entry</label>
    <nameField>
        <label>Queue Entry ID</label>
        <type>AutoNumber</type>
        <displayFormat>K_QE-{0}</displayFormat>
    </nameField>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <pluralLabel>Queue Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex/Main/classes/WSU_Kyou_Maintainer.cls
// This file is part of WSU_Kyou, a Salesforce native queue for Batch Apex and Scheduled Apex.

// Copyright 2014, Wayne State University
// License: 3-clause BSD license.  See LICENSE.

public class WSU_Kyou_Maintainer implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    private Integer nextPriority = null;
    private List<Integer> newOpenSlots = new List<Integer>();
    private Integer highestPriority = null;
    private Boolean wasLocked = false;

    public WSU_Kyou_Maintainer() {
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        List<WSU_Kyou_Info__c> kyouInfos = WSU_Kyou_Info__c.getAll().values();
        System.assertEquals(kyouInfos.size(), 1); // FIXME  Sanity check
        WSU_Kyou_Info__c kyouInfo = kyouInfos.get(0);
        if (kyouInfo.Locked__c) {
            wasLocked = true;
            return Database.getQueryLocator('select Id from User where Id =\'000000000000000000\''); // Do nothing
        } else {
            // Lock it
            kyouInfo.Locked__c = true;
            Database.SaveResult result = Database.Update(kyouInfo);
            return Database.getQueryLocator(
                'select Id, Data__c, Priority__c from WSU_Kyou_QueueEntry__c order by Priority__c'
            );
        }
    }

    public void execute(Database.BatchableContext bc, List<sObject> sobjs) {
        for (sObject entrysobj : sobjs) {
            WSU_Kyou_QueueEntry__c entry = (WSU_Kyou_QueueEntry__c)entrysobj;
            if (nextPriority == null) {
                nextPriority = 0; //  Default starting point
            }
            entry.Priority__c = nextPriority;
            if (highestPriority == null) {
                highestPriority = nextPriority;
            }
            newOpenSlots.add(nextPriority + 1);
            nextPriority += 2;
        }
        newOpenSlots.remove(newOpenSlots.size() - 1); // Remove the extra one on the end
        List<Database.SaveResult> results = Database.Update(sobjs);
    }

    public void finish(Database.BatchableContext bc) {
        if (!wasLocked) {
            WSU_Kyou.setOpenSlots(new Set<Integer>(newOpenSlots), [select Id from WSU_Kyou_Open_Slots__c]);

            List<WSU_Kyou_Info__c> kyouInfos = WSU_Kyou_Info__c.getAll().values();
            System.assertEquals(kyouInfos.size(), 1); // FIXME  sanity check
            WSU_Kyou_Info__c kyouInfo = kyouInfos.get(0);
            System.assert(kyouInfo.Locked__c); // FIXME: sanity check

            kyouInfo.Highest_Priority__c = highestPriority;
            kyouInfo.Lowest_Priority__c = nextPriority == null ? null : nextPriority - 2;

            // Unlock
            kyouInfo.Locked__c = false;

            Database.SaveResult result = Database.Update(kyouInfo);
        }
    }

    public class Kyou_MaintainerException extends Exception {}
}