objects/Main/objects/WSU_Kyou_Info__c.object
<!--
This file is part of WSU_Kyou, a Salesforce native queue for Batch Apex and Scheduled Apex.

Copyright 2013-2014, Wayne State University
License: 3-clause BSD license.  See LICENSE.
-->
<CustomObject>
    <description>Stores information about the state of entries in the Kyou.</description>
    <label>Kyou Info</label>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Lowest_Priority__c</fullName>
        <label>Lowest Priority</label>
        <type>Number</type>
        <precision>18</precision>
        <scale>0</scale>
    </fields>
    <fields>
        <fullName>Highest_Priority__c</fullName>
        <label>Highest Priority</label>
        <type>Number</type>
        <precision>18</precision>
        <scale>0</scale>
    </fields>
</CustomObject>

objects/Main/objects/WSU_Kyou_QueueEntry__c.object
<!--
This file is part of WSU_Kyou, a Salesforce native queue for Batch Apex and Scheduled Apex.

Copyright 2013-2014, Wayne State University
License: 3-clause BSD license.  See LICENSE.
-->
<CustomObject>
    <description>Entry in a Queue for Kyou.</description>
    <label>Queue Entry</label>
    <nameField>
        <label>Queue Entry ID</label>
        <type>AutoNumber</type>
        <displayFormat>K_QE-{0}</displayFormat>
    </nameField>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <pluralLabel>Queue Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Main/objects/WSU_Kyou_Saved_Add__c.object
<!--
This file is part of WSU_Kyou, a Salesforce native queue for Batch Apex and Scheduled Apex.

Copyright 2014, Wayne State University
License: 3-clause BSD license.  See LICENSE.
-->
<CustomObject>
    <description>Saved information on added entries.</description>
    <label>Kyou Saved Add</label>
    <nameField>
        <label>Saved Add ID</label>
        <type>AutoNumber</type>
        <displayFormat>K_SA-{0}</displayFormat>
    </nameField>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <type>LongTextArea</type>
        <length>32768</length>
    </fields>
    <pluralLabel>Kyou Saved Adds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

apex/Main/classes/WSU_KyouSavedAddsTest.cls
// This file is part of WSU_Kyou, a Salesforce native queue for Batch Apex and Scheduled Apex.

// Copyright 2014, Wayne State University
// License: 3-clause BSD license.  See LICENSE.

// The tests here are split off because of this bug:
// https://success.salesforce.com/issues_view?id=a1p300000008XM1AAM

@isTest
public class WSU_KyouSavedAddsTest {
    static testMethod void testFinishSavedAdds() {
        List<Database.SaveResult> results = Database.Insert(new List<sObject>{
            new WSU_Kyou_Saved_Add__c(
                Data__c = '[' +
                    '{' +
                        '"class":"WSU_Kyou_Batchable_Testing",' +
                        '"args":null,' +
                        '"size":null,' +
                        '"list":false,' +
                        '"object_list":false,' +
                        '"priority":7' +
                    '}' +
                ']'
            )
        });

        System.assertEquals([select count() from WSU_Kyou_QueueEntry__c], 0);

        Database.BatchableContext bc = null;
        WSU_Kyou kyou = new WSU_Kyou();
        Test.startTest();
        kyou.finish(bc);
        Test.stopTest();

        System.assertEquals([select count() from WSU_Kyou_QueueEntry__c], 1);
        System.assertEquals([select count() from WSU_Kyou_Saved_Add__c], 0);
        WSU_Kyou_Info__c kyouInfo = WSU_Kyou_Info__c.getAll().values().get(0);
        System.assertEquals(kyouInfo.Highest_Priority__c, 7);
        System.assertEquals(kyouInfo.Lowest_Priority__c, 7);
    }

}